ARMmbed/mbed-os-example-lorawan

lora_radio_helper.cpp
muRata modules do not have DIO4 and DIO5 interrupts connected.
=> Remove pins DIO4 and DIO5 from muRata modules

lora_radio_helper.cpp
To be merged after mbed-os 1c5c1c79d0b518aec629004be19f7fd1fd62fb8e has been taken into use
=> Change target names as new MTB namings

mbed-lora-radio-drv.lib, mbed-os.lib
Mbed-OS pointer points to feature-lorawan(latest commit for 5.8)
Radio driver pointer points to Master (with TXCO being driven high)
=> Updating  pointers

trace_helper.cpp
Trace helper was pulling in rtos bits which we may hamper
if we were to drop rtos for memory constrained platforms.
=> Trace helper modification

main.cpp
Since radio object is constructed by another source file, we have a
race condition. In order to prevent this race condition, LoRaWANInterface
object is now created in main().
=> Fix construction of LoRaWANInterface object

README.md
According to OOB testing (issue #42) we should add explanation that network credentials are typically provided by LoRa network provider.
=> Added more info about network credentials

trace_helper.cpp
Use Serial object instead of stdout for trace prints. This is also
logical as we construct Serial object in the beginning of the source file.
Also this enables easier tracing with new targets where stdout might not
work at the beginning.
=> Use Serial object for trace prints

README.md, main.cpp, mbed_app.json
Fix for issue #58.
Our currently supported targets DISCO_L072CZ_LRWAN1 and MTB_MURATA_ABZ
only have 20kB of RAM which requires some memory usage optimizations
to LoRa example application especially when compiled with GCC compiler.
This commit reduces application tx and rx buffers to 30 bytes (instead of
255) as application only sends short messages.
Also main thread stack size is reduced to 1024 bytes for these two targets.
NOTE! Due to small stack size, mbed traces cannot be enabled for these targets!
=> Reduce example application memory usage

lora_radio_helper.h, main.cpp, mbed_app.json
mbed-os-example-lorawan project is now CI tested only for targets which really have lora HW (mbed-os commit b61912cbbed16cf5262ec88376738aec65413741). Therefore DEVICE_SPI and MBED_CONF_APP_LORAWAN_ENABLED are no longer needed.
This fixes issues #62 and #63.
=> Remove usage of DEVICE_SPI and MBED_CONF_APP_LORAWAN_ENABLED flags

Jenkinsfile
Legacy alignment has been restored in mbed-os, therefore we can enable ARMC6 compiler again.
=> Enabled ARMC6 compiler

main.cpp
We're being a bad citizen for networks right now. We send as fast as possible and send messages confirmed. Our official example should show the right way of building LoRaWAN devices.
@hasnainvirk @AnttiKauppila
=> Should send unconfirmed by default

Jenkinsfile
* Removed ARMC6 as ARM builds with c6 now
* Removed compilerLabel variable and just used toolchains as labels directly (ARM, GCC_ARM, IAR)
Build results: https://mbed-os.mbedcloudtesting.com/view/Cellular/job/mbed-os-example-lorawan-pipeline/job/toolchain_update/
=> ARM builds as ARMC6 now, simplified toolchains

Jenkinsfile
About 5% of our builds are failing due to mbed-cli caching issue (ERROR: File exists). This is a workaround until it is fixed.
=> Retry if mbed deploy fails

mbed_app.json
Adds configuration for IM880B.
The iM880B is a compact and low-cost radio module that operates in the unlicensed 868 MHz band and combines a powerful Cortex-M3 controller with the new LoRa® transceiver SX1272 of Semtech Corporation.
More details available at https://wireless-solutions.de/products/radiomodules/im880b-l.html
=> add target IM880B

README.md, mbed-os.lib, mbed_app.json
This PR adds support for the Embedded Planet Agora target (`EP_AGORA`), and also updates the example to use mbed-os 5.14.0.
=> Add support for the Embedded Planet Agora target

Jenkinsfile
Jenkinsfile: disable IAR build
- IAR build disabled due to license issue
=> Jenkinsfile: disable IAR build

Jenkinsfile
Jenkinsfile: removed MTB targets
- Removed MTB targets from Jenkinsfile which are not supported in mbed-os master anymore
=> Jenkinsfile: removed MTB targets

config/SX126X_example_config.json, config/SX127X_example_config.json, mbed-lora-radio-drv.lib, mbed_app.json
Lora drivers are now (since mbed-os 6.0) included in mbed-os so separate driver repository is no longer needed.
=> Use lora drivers from mbed-os repository

.travis.yml, mbed-os.lib
This pull request updates the example to be compatible with the 
mbed-os-6.6.0 release of mbed-os.
=> Update for mbed-os-6.6.0

CMakeLists.txt
The dependency on TLS is now handled by Mbed OS
Depends on https://github.com/ARMmbed/mbed-os/pull/14098
=> CMake: Remove unnecessary library addition

README.md, lora_radio_helper.h, mbed_app.json
Hi
After https://github.com/ARMmbed/mbed-os/pull/14249
merge in mbed-os
NUCLEO_WL55JC is now LoRa capable by default.
Thx
@ludoch-stm
@ARMmbed/team-st-mcd
@MarceloSalazar
=> STM32WL : NUCLEO_WL55JC support

CMakeLists.txt, README.md
This PR
* Updates README with outdated information removed and Mbed CLI 2 instructions added
* Adds necessary CMake declaration (see [documentation](https://github.com/ARMmbed/mbed-os-5-docs/blob/development/docs/porting/custom-target-porting.md#preparing-1)) for the custom target, to fix `mbed-tools compile -t GCC_ARM -m K64F_SX126X`.
=> CMake: Fix custom target and add instructions

mbed_app.json
This PR updates this example to use the new Arduino pin names (e.g. D0 -> ARDUINO_UNO_D0).
=> Update Arduino pin names

mbed-os.lib, mbed_app.json
This pull request updates the example to be compatible with the 
mbed-os-6.11.0 release of mbed-os.
=> Update for mbed-os-6.11.0

mbed_app.json
2 minor patches:
- .mbed file should not in git files
- mbed-trace option is added in mbbed_app.json : no impact as default value is false, but helps customer to enable it
=> Minor patches for example easy usage

mbed-os.lib, mbed_app.json
This pull request updates the example to be compatible with the 
mbed-os-6.12.0 release of mbed-os.
=> Update for mbed-os-6.12.0

lora_radio_helper.h
Hi
STM32WL_LoRaRadio class has been updated in https://github.com/ARMmbed/mbed-os/pull/14734
@hallard
=> Update lora_radio_helper.h for STM32WL_LoRaRadio

lora_radio_helper.h, mbed-os.lib
This pull request updates the example to be compatible with the 
mbed-os-6.13.0 release of mbed-os.
=> Update for mbed-os-6.13.0
